site:
  title: 學藝不精工程師 技術筆記
  url: https://novice-engineer.github.io/
  start_page: novice-engineer-notes::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: ./docs/ui

asciidoc:
  attributes:
    page-pagination: ''
    source-highlighter: highlightjs
    icons: font
