<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.buckethsu</groupId>
    <artifactId>bucket-hsu-notes</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <asciidoctor.maven.plugin.version>3.2.0</asciidoctor.maven.plugin.version>
        <asciidoctorj.version>3.0.1</asciidoctorj.version>
        <asciidoctorj.diagram.version>3.1.0</asciidoctorj.diagram.version>
        <jruby.version>9.4.12.0</jruby.version>
        <maven.resources.plugin.version>3.3.1</maven.resources.plugin.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>${asciidoctor.maven.plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.jruby</groupId>
                        <artifactId>jruby-complete</artifactId>
                        <version>${jruby.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj</artifactId>
                        <version>${asciidoctorj.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-diagram</artifactId>
                        <version>${asciidoctorj.diagram.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/docs</sourceDirectory>
                    <outputDirectory>${project.build.directory}/generated-docs</outputDirectory>
                    <backend>html5</backend>
                    <relativeBaseDir>true</relativeBaseDir>
                    <preserveDirectories>true</preserveDirectories>
                    <requires>
                        <require>asciidoctor-diagram</require>
                    </requires>
                    <attributes>
                        <icons>font</icons>
                        <iconfont-remote>true</iconfont-remote>
                        <source-highlighter>highlight.js</source-highlighter>
                        <sectanchors>true</sectanchors>
                        <idprefix/>
                        <idseparator>-</idseparator>
                        <last-update-label/>
                    </attributes>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-html-docs</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven.resources.plugin.version}</version>
                <executions>
                    <execution>
                        <id>copy-static-assets</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/generated-docs</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/src/docs</directory>
                                    <includes>
                                        <include>.nojekyll</include>
                                        <include>stylesheets/**</include>
                                        <include>images/**</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
