= SQL 日期時間格式轉換：SQL Server、Oracle 9i、DB2
學藝不精工程師
:experimental:
:icons: font
:sectnums:
:toc: left
:toc-title: 目錄
:toclevels: 3
:source-highlighter: highlight.js
:last-update-label!:
:nofooter:

本頁整理 SQL Server、Oracle 9i 與 DB2 的日期時間取得、字串格式轉換，以及台灣民國年月日的常用寫法。

NOTE: 範例中的輸出結果以 `2026-07-17 09:08:07` 為示意。實際結果會依資料庫伺服器的目前時間與語系設定而不同。

== 快速對照

[cols="22%,26%,26%,26%", options="header"]
|===
|用途 |SQL Server |Oracle 9i |DB2

|目前日期時間
|`GETDATE()`
|`SYSDATE`
|`CURRENT TIMESTAMP`

|目前日期
|`CAST(GETDATE() AS date)`
|`TRUNC(SYSDATE)`
|`CURRENT DATE`

|年月日 `YYYYMMDD`
|`CONVERT(char(8), GETDATE(), 112)`
|`TO_CHAR(SYSDATE, 'YYYYMMDD')`
|`VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD')`

|民國年月日數字
|西元年月日數字減 `19110000`
|西元年月日數字減 `19110000`
|西元年月日數字減 `19110000`
|===

== SQL Server

=== 取得目前日期時間

[source,sql]
----
SELECT GETDATE() AS CURRENT_DATETIME;
----

輸出示意：

[source,text]
----
2026-07-17 09:08:07.123
----

=== 常用 CONVERT 日期格式

SQL Server 可用 `CONVERT(varchar, 日期時間, style)` 轉換輸出格式。

[source,sql]
----
SELECT CONVERT(varchar(30), GETDATE(), 100) AS STYLE_100; -- Jul 17 2026  9:08AM
SELECT CONVERT(char(10),    GETDATE(), 101) AS STYLE_101; -- 07/17/2026
SELECT CONVERT(char(10),    GETDATE(), 102) AS STYLE_102; -- 2026.07.17
SELECT CONVERT(char(10),    GETDATE(), 103) AS STYLE_103; -- 17/07/2026
SELECT CONVERT(char(10),    GETDATE(), 104) AS STYLE_104; -- 17.07.2026
SELECT CONVERT(char(10),    GETDATE(), 105) AS STYLE_105; -- 17-07-2026
SELECT CONVERT(varchar(11), GETDATE(), 106) AS STYLE_106; -- 17 Jul 2026
SELECT CONVERT(varchar(12), GETDATE(), 107) AS STYLE_107; -- Jul 17, 2026
SELECT CONVERT(char(8),     GETDATE(), 108) AS STYLE_108; -- 09:08:07
SELECT CONVERT(varchar(30), GETDATE(), 109) AS STYLE_109; -- Jul 17 2026  9:08:07:123AM
SELECT CONVERT(char(10),    GETDATE(), 110) AS STYLE_110; -- 07-17-2026
SELECT CONVERT(char(10),    GETDATE(), 111) AS STYLE_111; -- 2026/07/17
SELECT CONVERT(char(8),     GETDATE(), 112) AS STYLE_112; -- 20260717
SELECT CONVERT(varchar(24), GETDATE(), 113) AS STYLE_113; -- 17 Jul 2026 09:08:07:123
SELECT CONVERT(varchar(12), GETDATE(), 114) AS STYLE_114; -- 09:08:07:123
SELECT CONVERT(char(19),    GETDATE(), 120) AS STYLE_120; -- 2026-07-17 09:08:07
SELECT CONVERT(varchar(23), GETDATE(), 121) AS STYLE_121; -- 2026-07-17 09:08:07.123
SELECT CONVERT(varchar(23), GETDATE(), 126) AS STYLE_126; -- 2026-07-17T09:08:07.123
----

NOTE: `varchar` 長度不足時，結果會被截斷。固定格式可使用 `char(n)`；長度可能因月份英文或 AM/PM 改變時，應使用足夠長的 `varchar(n)`。

=== 年月與年月日基本範例

[source,sql]
----
-- YYYY-MM
SELECT CONVERT(char(7), GETDATE(), 126) AS YEAR_MONTH;

-- YYYY-MM-DD
SELECT CONVERT(char(10), GETDATE(), 23) AS ISO_DATE;

-- YYYYMMDD
SELECT CONVERT(char(8), GETDATE(), 112) AS COMPACT_DATE;

-- YYYY/MM/DD
SELECT CONVERT(char(10), GETDATE(), 111) AS SLASH_DATE;

-- YYYY-MM-DD HH:MM:SS
SELECT CONVERT(char(19), GETDATE(), 120) AS DATETIME_TEXT;
----

輸出示意：

[source,text]
----
YEAR_MONTH    = 2026-07
ISO_DATE      = 2026-07-17
COMPACT_DATE  = 20260717
SLASH_DATE    = 2026/07/17
DATETIME_TEXT = 2026-07-17 09:08:07
----

=== 使用字串函式組合格式

[source,sql]
----
-- YYYY MM DD
SELECT REPLACE(CONVERT(char(10), GETDATE(), 111), '/', ' ') AS DATE_WITH_SPACES;

-- Mon YYYY，例如 Jul 2026
SELECT RIGHT(CONVERT(varchar(11), GETDATE(), 106), 8) AS MONTH_YEAR;
----

=== 台灣民國年月日

==== 數字格式：YYYMMDD

將西元 `YYYYMMDD` 轉為整數後減去 `19110000`。

[source,sql]
----
SELECT
    CONVERT(int, CONVERT(char(8), GETDATE(), 112)) - 19110000 AS TW_DATE;
----

以西元 `2026-07-17` 為例，結果為：

[source,text]
----
1150717
----

==== 固定 7 碼字串格式：YYYMMDD

[source,sql]
----
SELECT
    RIGHT(
        '0000000' + CAST(
            CONVERT(int, CONVERT(char(8), GETDATE(), 112)) - 19110000
            AS varchar(7)
        ),
        7
    ) AS TW_DATE;
----

這個版本可確保民國年不足三碼時仍補零，例如民國 99 年輸出 `0990101`。

==== 帶分隔符號格式：YYY/MM/DD

[source,sql]
----
DECLARE @TW_DATE char(7);

SET @TW_DATE = RIGHT(
    '0000000' + CAST(
        CONVERT(int, CONVERT(char(8), GETDATE(), 112)) - 19110000
        AS varchar(7)
    ),
    7
);

SELECT
    STUFF(STUFF(@TW_DATE, 4, 0, '/'), 7, 0, '/') AS TW_DATE;
----

輸出示意：

[source,text]
----
115/07/17
----

== Oracle 9i

Oracle 9i 以 `SYSDATE` 取得目前日期時間，格式化時使用 `TO_CHAR`。

=== 取得目前日期時間

[source,sql]
----
SELECT SYSDATE AS CURRENT_DATETIME
FROM DUAL;
----

=== 常用日期格式

[source,sql]
----
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')              AS ISO_DATE       FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD')                AS COMPACT_DATE   FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD')              AS SLASH_DATE     FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY')              AS DAY_FIRST      FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS')              AS TIME_TEXT      FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')   AS DATETIME_TEXT  FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS ISO_DATETIME FROM DUAL;
----

輸出示意：

[source,text]
----
ISO_DATE      = 2026-07-17
COMPACT_DATE  = 20260717
SLASH_DATE    = 2026/07/17
DAY_FIRST     = 17/07/2026
TIME_TEXT     = 09:08:07
DATETIME_TEXT = 2026-07-17 09:08:07
ISO_DATETIME  = 2026-07-17T09:08:07
----

=== 年月基本範例

[source,sql]
----
SELECT TO_CHAR(SYSDATE, 'YYYY-MM') AS YEAR_MONTH
FROM DUAL;
----

=== 台灣民國年月日

==== 數字格式：YYYMMDD

[source,sql]
----
SELECT
    TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD')) - 19110000 AS TW_DATE
FROM DUAL;
----

==== 固定 7 碼字串格式：YYYMMDD

[source,sql]
----
SELECT
    LPAD(
        TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD')) - 19110000),
        7,
        '0'
    ) AS TW_DATE
FROM DUAL;
----

==== 帶分隔符號格式：YYY/MM/DD

[source,sql]
----
SELECT
    SUBSTR(TW_DATE, 1, 3) || '/' ||
    SUBSTR(TW_DATE, 4, 2) || '/' ||
    SUBSTR(TW_DATE, 6, 2) AS TW_DATE
FROM (
    SELECT LPAD(
               TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD')) - 19110000),
               7,
               '0'
           ) AS TW_DATE
    FROM DUAL
);
----

NOTE: Oracle 的 `DATE` 型別本身包含日期與秒級時間。顯示格式可能受 `NLS_DATE_FORMAT` 影響，因此正式查詢建議明確使用 `TO_CHAR` 指定格式。

== DB2

DB2 可使用 `CURRENT DATE` 取得日期，使用 `CURRENT TIMESTAMP` 取得日期時間。

=== 取得目前日期與時間

[source,sql]
----
SELECT CURRENT DATE AS CURRENT_DATE_VALUE
FROM SYSIBM.SYSDUMMY1;

SELECT CURRENT TIMESTAMP AS CURRENT_TIMESTAMP_VALUE
FROM SYSIBM.SYSDUMMY1;
----

=== 使用 VARCHAR_FORMAT 的常用格式

[source,sql]
----
SELECT VARCHAR_FORMAT(CURRENT DATE, 'YYYY-MM-DD') AS ISO_DATE
FROM SYSIBM.SYSDUMMY1;

SELECT VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD') AS COMPACT_DATE
FROM SYSIBM.SYSDUMMY1;

SELECT VARCHAR_FORMAT(CURRENT DATE, 'YYYY/MM/DD') AS SLASH_DATE
FROM SYSIBM.SYSDUMMY1;

SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'HH24:MI:SS') AS TIME_TEXT
FROM SYSIBM.SYSDUMMY1;

SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS DATETIME_TEXT
FROM SYSIBM.SYSDUMMY1;
----

=== 不使用 VARCHAR_FORMAT 的相容寫法

部分較舊或設定不同的 DB2 環境可使用 `YEAR`、`MONTH`、`DAY` 與 `DIGITS` 組合。

[source,sql]
----
-- YYYYMMDD
SELECT
    DIGITS(YEAR(CURRENT DATE)) ||
    DIGITS(MONTH(CURRENT DATE)) ||
    DIGITS(DAY(CURRENT DATE)) AS COMPACT_DATE
FROM SYSIBM.SYSDUMMY1;
----

若環境中的 `DIGITS` 對整數輸出長度不符合預期，可使用 `RIGHT` 補零：

[source,sql]
----
SELECT
    VARCHAR(YEAR(CURRENT DATE)) ||
    RIGHT('00' || VARCHAR(MONTH(CURRENT DATE)), 2) ||
    RIGHT('00' || VARCHAR(DAY(CURRENT DATE)), 2) AS COMPACT_DATE
FROM SYSIBM.SYSDUMMY1;
----

=== 年月與日期時間基本範例

[source,sql]
----
-- YYYY-MM
SELECT VARCHAR_FORMAT(CURRENT DATE, 'YYYY-MM') AS YEAR_MONTH
FROM SYSIBM.SYSDUMMY1;

-- YYYY-MM-DD
SELECT VARCHAR_FORMAT(CURRENT DATE, 'YYYY-MM-DD') AS ISO_DATE
FROM SYSIBM.SYSDUMMY1;

-- YYYY-MM-DD HH:MM:SS
SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS DATETIME_TEXT
FROM SYSIBM.SYSDUMMY1;
----

=== 台灣民國年月日

==== 使用 VARCHAR_FORMAT：數字格式 YYYMMDD

[source,sql]
----
SELECT
    INTEGER(VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD')) - 19110000 AS TW_DATE
FROM SYSIBM.SYSDUMMY1;
----

==== 不使用 VARCHAR_FORMAT：數字格式 YYYMMDD

[source,sql]
----
SELECT
    INTEGER(
        VARCHAR(YEAR(CURRENT DATE)) ||
        RIGHT('00' || VARCHAR(MONTH(CURRENT DATE)), 2) ||
        RIGHT('00' || VARCHAR(DAY(CURRENT DATE)), 2)
    ) - 19110000 AS TW_DATE
FROM SYSIBM.SYSDUMMY1;
----

==== 固定 7 碼字串格式：YYYMMDD

[source,sql]
----
SELECT
    RIGHT(
        '0000000' || VARCHAR(
            INTEGER(VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD')) - 19110000
        ),
        7
    ) AS TW_DATE
FROM SYSIBM.SYSDUMMY1;
----

==== 帶分隔符號格式：YYY/MM/DD

[source,sql]
----
SELECT
    SUBSTR(TW_DATE, 1, 3) || '/' ||
    SUBSTR(TW_DATE, 4, 2) || '/' ||
    SUBSTR(TW_DATE, 6, 2) AS TW_DATE
FROM (
    SELECT RIGHT(
               '0000000' || VARCHAR(
                   INTEGER(VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD')) - 19110000
               ),
               7
           ) AS TW_DATE
    FROM SYSIBM.SYSDUMMY1
) T;
----

== 三種資料庫的民國年月日對照

[source,sql]
----
-- SQL Server
SELECT CONVERT(int, CONVERT(char(8), GETDATE(), 112)) - 19110000 AS TW_DATE;

-- Oracle 9i
SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD')) - 19110000 AS TW_DATE
FROM DUAL;

-- DB2
SELECT INTEGER(VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD')) - 19110000 AS TW_DATE
FROM SYSIBM.SYSDUMMY1;
----

== 注意事項

* 日期時間型別應盡量保留原始型別，只有顯示、匯出或組合文字時才轉成字串。
* 不要使用格式化後的日期字串直接做日期加減，應先以日期型別運算，再於最後一步格式化。
* `GETDATE()`、`SYSDATE`、`CURRENT DATE` 與 `CURRENT TIMESTAMP` 取的是資料庫伺服器時間，不一定等於使用者電腦時間。
* 民國日期的減法寫法適用於一般西元年月日數字轉換，但輸出是應用格式，不是資料庫原生日期型別。
* 欄位別名統一使用 `TW_DATE`，避免同一份文件混用 `ROC_DATE`、`rocDate` 等名稱。

== 原始參考

* https://dotblogs.com.tw/kevinya/2014/09/05/146474[各式各樣的 GETDATE() 時間格式轉換 CONVERT]
